#!/usr/bin/env node
// Vietnamese narration for the quick-start guide: macOS "Linh" voice (say) + ffmpeg.
// Reads docs/guides/father-quick-start/scenes.js; writes audio/<scene>.m4a and timings.js
// (sentence start/end seconds, used for synchronized captions in the page and the video).
// Usage: node scripts/father_guide/tts.mjs [scene-id ...]
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import os from 'node:os';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..');
const dir = path.join(root, 'docs/guides/father-quick-start');
const ctx = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(dir, 'scenes.js'), 'utf8'), ctx);
const scenes = ctx.window.GUIDE.scenes;

// The Vietnamese voice reads English words letter by letter, so give it Vietnamese spellings.
// Longest keys first; the on-screen caption keeps the original spelling.
const say = [
  ['OPEN_CHURCH.html', 'ô-pần chớt, chấm, hát-ti-em-eo'],
  ['Thach_Bi_Viewer', 'Thạch Bi Viu-ơ'],
  ['index.html', 'in-đéc, chấm, hát-ti-em-eo'],
  ['2026-10-07', 'hai nghìn không trăm hai mươi sáu, mười, không bảy'],
  ['00-overview', 'không không, âu-vơ-viu'],
  ['Download ZIP', 'đao-lốt zíp'], ['Downloads', 'đao-lốt'], ['Extract All', 'éch-trắc ôn'], ['Extract', 'éch-trắc'],
  ['Cinematic tour', 'xi-nê-ma-tích tua'], ['Technical tours', 'téc-ni-cồ tua'], ['Go inside', 'gô in-xai'],
  ['W, A, S, D', 'đáp-bồ-liu, ây, ét, đi'],
  ['references', 'ré-phơ-rần-xợ'], ['References', 'ré-phơ-rần-xợ'], ['Simulator', 'xim-miu-lây-tơ'],
  ['Sanctuary', 'xăng-chiu-a-ri'], ['Discover', 'đít-cớ-vơ'], ['GitHub', 'git-hấp'], ['Windows', 'uyn-đâu'],
  ['megabyte', 'mê-ga-bai'], ['internet', 'in-tơ-nét'], ['organ', 'oóc-gân'], ['Enter', 'en-tơ'],
  ['Chrome', 'crôm'], ['Edge', 'ét'], ['Code', 'cốt'], ['ZIP', 'zíp'], ['Mac', 'mác'], ['Esc', 'ét-cếp'], ['Nave', 'nêv'],
];
const spoken = (s) => say.reduce((t, [k, v]) => t.split(k).join(v), s.replace(/\*\*/g, ''));

const only = process.argv.slice(2);
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tts-'));
fs.mkdirSync(path.join(dir, 'audio'), { recursive: true });
const timingsFile = path.join(dir, 'timings.js');
let timings = {};
if (fs.existsSync(timingsFile)) {
  const c2 = { window: {} }; vm.runInNewContext(fs.readFileSync(timingsFile, 'utf8'), c2); timings = c2.window.TIMINGS || {};
}
const run = (cmd, args) => execFileSync(cmd, args, { stdio: ['ignore', 'ignore', 'inherit'] });
const duration = (f) => parseFloat(execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]).toString());

for (const sc of scenes) {
  if (only.length && !only.includes(sc.id)) continue;
  const parts = [], marks = [];
  let at = 0.25;
  const lead = path.join(tmp, `${sc.id}-lead.wav`);
  run('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'anullsrc=r=44100:cl=mono', '-t', '0.25', lead]);
  parts.push(lead);
  sc.sentences.forEach((s, i) => {
    const aiff = path.join(tmp, `${sc.id}-${i}.aiff`), wav = path.join(tmp, `${sc.id}-${i}.wav`);
    run('say', ['-v', 'Linh', '-r', '170', '-o', aiff, spoken(s)]);
    run('ffmpeg', ['-y', '-loglevel', 'error', '-i', aiff, '-ar', '44100', '-ac', '1', wav]);
    const d = duration(wav);
    marks.push({ start: +at.toFixed(2), end: +(at + d).toFixed(2) });
    parts.push(wav); at += d;
    const gap = path.join(tmp, `${sc.id}-${i}-gap.wav`), gd = i < sc.sentences.length - 1 ? 0.4 : 0.5;
    run('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'anullsrc=r=44100:cl=mono', '-t', String(gd), gap]);
    parts.push(gap); at += gd;
  });
  const list = path.join(tmp, `${sc.id}.txt`);
  fs.writeFileSync(list, parts.map((p) => `file '${p}'`).join('\n'));
  const out = path.join(dir, 'audio', `${sc.id}.m4a`);
  run('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'concat', '-safe', '0', '-i', list, '-af', 'loudnorm=I=-16:TP=-1.5:LRA=11', '-ar', '44100', '-ac', '1', '-c:a', 'aac', '-b:a', '80k', out]);
  timings[sc.id] = { duration: +duration(out).toFixed(2), sentences: marks };
  console.log(sc.id, timings[sc.id].duration + ' s');
}
fs.writeFileSync(timingsFile, '// Generated by scripts/father_guide/tts.mjs: sentence timings of audio/<scene>.m4a (seconds).\nwindow.TIMINGS = ' + JSON.stringify(timings, null, 1) + ';\n');
fs.rmSync(tmp, { recursive: true, force: true });
