#!/usr/bin/env python3
"""Package native PNG bytes for WebGL-safe double-clicked file: viewing.

No resampling/image editing. Originals and their generation provenance remain
the owners; the generated JS only gives two shared textures same-origin data
URLs. Rebuild after replacing an explicitly approved native artwork revision.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FOLDER = ROOT / "Thach_Bi_Viewer/references/10-wing-saints"
OUTPUT = ROOT / "Thach_Bi_Viewer/wing-saint-textures.js"


def packaged_source():
    provenance = json.loads((FOLDER / "provenance.json").read_text())
    textures = {}
    for asset in provenance["assets"]:
        filename = asset["file"]
        if Path(filename).name != filename:
            raise ValueError("Artwork file must belong to its provenance folder")
        native = (FOLDER / filename).read_bytes()
        if hashlib.sha256(native).hexdigest() != asset["sha256"]:
            raise ValueError("Native bytes differ from recorded provenance: " + filename)
        textures["references/10-wing-saints/" + filename] = {
            "sha256": asset["sha256"],
            "width": asset["nativeWidth"], "height": asset["nativeHeight"],
            "imageUrl": "data:image/png;base64," + base64.b64encode(native).decode("ascii"),
        }
    return ("/* Generated by scripts/build_saint_textures.py. Native concept PNG\n"
            " * bytes preserved; two shared textures, no image resampling.\n"
            " * Keeps ordinary offline file: WebGL uploads same-origin. */\n"
            "window.CHURCH_WING_SAINT_TEXTURES = "
            + json.dumps(textures, ensure_ascii=True, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify deterministic native packaging without rewriting")
    args = parser.parse_args()
    source = packaged_source()
    if args.check:
        if OUTPUT.read_text() != source:
            raise SystemExit("STALE offline saint texture package; rebuild it")
        print("PASS native hashes and deterministic offline texture package")
    else:
        OUTPUT.write_text(source)
        print("Packaged two native concept PNG textures without resampling")
