"""Markdown for the electrical safety and efficiency review. All numbers come from the result of
build_electrical_safety_review.analyse(); the wording states what each number is and is not."""
from __future__ import annotations


def n(value, digits=0):
    if value is None: return '–'
    text = f'{value:,.{digits}f}'
    return text


def table(head, rows, align=None):
    align = align or ['---'] + ['---:'] * (len(head) - 1)
    out = ['| ' + ' | '.join(head) + ' |', '| ' + ' | '.join(align) + ' |']
    out += ['| ' + ' | '.join(str(c) for c in row) + ' |' for row in rows]
    return '\n'.join(out)


def write_report(r, issue_date):
    s1, s2 = r['supply']
    e = r['energy']
    circuits = r['circuits']
    by = {c['circuit']: c for c in circuits}
    zones = r['zones']
    sep = r['separation']['totals']
    life = r['life_safety']
    scenes = {x['scene']: x for x in e['scenes']}
    full = scenes[r['default_scene']]
    fixed = [c for c in circuits if c['socket_rating_a'] is None]
    sockets = [c for c in circuits if c['socket_rating_a']]
    tight = min(fixed, key=lambda c: c['cases'][0]['loop_allowance_ohm_type_c_at_minimum'])
    busiest = max(fixed, key=lambda c: c['cases'][0]['loading_percent'])
    open_points = sum(z['open_to_weather'] for z in zones)
    covered_points = sum(z['covered_exterior'] for z in zones)
    highest = max(x['highest_point_m'] for x in r['exterior_circuits'])
    ceiling = [f for f in r['fans'] if f['type'] == 'fanCeiling']
    other_fans = [f for f in r['fans'] if f['type'] != 'fanCeiling']
    exterior_light = [c for c in circuits if c['kind'] == 'light' and c['exterior_points']]
    exterior_w = sum(c['full_service_w'] for c in exterior_light)
    light_w = full['by_category_w']['light']
    feeder = {f['area_mm2']: f for f in s1['db2_feeder']}
    reach = r['within_reach']
    reach_kinds = {}
    for x in reach: reach_kinds[x['category']] = reach_kinds.get(x['category'], 0) + 1
    timber = r['timber_roof_and_lining_mains_m']
    top = sorted(circuits, key=lambda c: -c['full_service_w'])[:6]
    fan_by = {f['type']: f for f in e['fans']}
    cf = fan_by['fanCeiling']['speeds']

    out = []
    w = out.append
    w(f'# Electrical walk-round: safety and efficiency review · {issue_date}')
    w('')
    w('Status: **DERIVED / CONCEPT / ENGINEERING HOLD**. This is a review of the default simulator model, zone by zone, with conditional calculations. '
      'It is not a wiring design, a compliance statement or permission to buy, build or energise. The supply, earthing, fault level, products, cable types and '
      'installation methods are still unknown ([questions Q01–Q15 and Q42–Q44](../engineering/questions-for-parish-and-designers.json)); every current, cable size and '
      'fault value below is a comparison on stated assumptions, to be replaced by the responsible electrical engineer\'s checked design.')
    w('')
    w('Generated by `python3 scripts/build_electrical_safety_review.py` from the same model revision as the exports in this folder '
      f'({r["counts"]["shown_items"]} shown items, {r["counts"]["wired_points"]} wired points, {r["counts"]["routes"]} routes, {r["counts"]["mains_circuits"]} mains circuits). '
      'Do not edit the numbers by hand: change the model or the stated assumptions and rebuild. Evidence, pictures and machine-readable results: '
      '[review/electrical-safety-2026-10-09](../../review/electrical-safety-2026-10-09/README.md).')
    w('')
    w('## 1. Result in brief')
    w('')
    w(f'- **Fixed equipment** (lights, fans, exit signs; catalogue maximum, known subset): **{n(s1["fixed_known_w"])} W**. With the 25 % planning reserve that is '
      f'{n(s1["fixed_planning_a"], 1)} A at 230 V / PF 0.9 and {n(s2["fixed_planning_a"], 1)} A at 220 V / PF 0.8. The AV rack is not included: its mains input is unknown.')
    w(f'- **Socket circuits** add their ratings on top: {n(s1["indoor_socket_rating_a"])} A indoors (P1, P2) and {n(s1["event_socket_rating_a"])} A at the towers (P3, P4). '
      f'On one phase everything together is **{n(s1["single_phase_everything_a"], 0)} A**; shared over three phases it is about '
      f'**{n(max(s1["three_phase_a"]), 0)} A per phase**. A single-phase supply cannot carry the event points with the rest of the church.')
    w(f'- **Protection screens**: comparison breakers are chosen at 1.25 × design current, so no fixed circuit loads its breaker above 80 %; the fullest is {busiest["circuit"]} at {n(busiest["cases"][0]["loading_percent"], 0)} %. '
      f'With an ideal supply, a far-end earth fault would trip a type C breaker at once on every circuit even at the smallest usual cable; the least margin is on '
      f'{tight["circuit"]} ({n(tight["cases"][0]["fault_a_at_minimum"], 0)} A against {n(10 * tight["cases"][0]["comparison_breaker_a"], 0)} A). The real supply and feeder will reduce these currents.')
    harsher = [c['circuit'] for c in fixed if c['cases'][1]['comparison_area_mm2'] != c['cases'][1]['minimum_area_mm2']]
    w(f'- **Voltage drop and cable size**: in case S1 every lighting and fan circuit passes the comparison with 1.5 or 2.5 mm², with the load spread along the route as modelled. '
      f'In the hotter, more bunched case S2, {", ".join(harsher)} need a larger size. '
      f'The two indoor socket circuits fail in both cases at 2.5 mm²: {n(by["P1"]["cases"][0]["vdrop_percent_at_minimum_area"], 1)} % and {n(by["P2"]["cases"][0]["vdrop_percent_at_minimum_area"], 1)} % drop with 16 A at the mid-nave outlet.')
    w(f'- **Energy**: the full evening service is modelled at **{n(full["watts"])} W**, {n(full["kwh_per_service"], 2)} kWh per service and {n(full["kwh_per_month"])} kWh per month at '
      f'{n(e["services_per_month"])} services. Exterior lighting takes {n(100 * exterior_w / light_w)} % of the lighting power in that scene. Cable losses are about {n(e["loss_percent_minimum_areas"], 1)} %.')
    w('')
    w('### Findings in order of importance')
    w('')
    rows = [
        ['1', 'Supply and phases', f'{n(s1["single_phase_everything_a"])} A on one phase with all sockets at their rating ({n(s2["single_phase_everything_a"])} A at 220 V / PF 0.8); '
         f'about {n(max(s1["three_phase_a"]))} A per phase on three phases. The simulator\'s 63 A main-switch graphic covers neither.',
         'Decide the supply (phases, capacity) and which loads may run together: Q01, Q08, Q42, Q43. Electrical engineer with the utility.'],
        ['2', 'DB-1 → DB-2 feeder', f'{n(s1["db2_feeder_m"], 1)} m. With both event points on one phase: {n(feeder[25]["single_phase_with_events_percent"], 1)} % drop at 25 mm² and '
         f'{n(feeder[50]["single_phase_with_events_percent"], 1)} % at 50 mm². On three balanced phases: {n(feeder[10]["three_phase_with_events_percent"], 1)} % at 10 mm², '
         f'{n(feeder[16]["three_phase_with_events_percent"], 1)} % at 16 mm².',
         'A three-phase feeder, or a separate event supply at the front. Not designed: Q42.'],
        ['3', 'Older cable report method', 'The route-level engine (`electrical_review.py`) predates the outlets. It adds the socket allowance as a load with the 25 % reserve and gives the '
         'event circuits a lighting-style drop share, which would print about 70 mm² for P3/P4 and "no candidate" for the feeder.',
         'Do not rebuild `output/electrical-review/` for the socket circuits until that method is revised and independently checked. This review sizes sockets by their rating.'],
        ['4', 'Indoor socket circuits P1, P2', f'{n(by["P1"]["longest_path_m"], 1)} m and {n(by["P2"]["longest_path_m"], 1)} m to the mid-nave outlets. 2.5 mm² fails the drop screen and the '
         f'S1 ampacity screen; the comparison gives {by["P1"]["cases"][0]["comparison_area_mm2"]} mm² (S1) or {by["P1"]["cases"][1]["comparison_area_mm2"]} mm² (S2). '
         f'Only {n(by["P2"]["cases"][0]["loop_allowance_ohm_type_c_at_minimum"], 2)} Ω is left for supply and board before a C16 stops tripping at once at 2.5 mm².',
         'Larger conductors, a lower rating, or one circuit per outlet pair; 30 mA residual-current protection stays essential. Q44.'],
        ['5', 'Loudspeaker lines beside mains', f'{n(sep["audio"]["within_0_30_m"])} m of the {n(sep["audio"]["length_m"])} m of loudspeaker route lies within 0.30 m of a mains route, '
         f'{n(sep["audio"]["within_0_05_m"])} m on the same line. Microphone lines are separate ({n(sep["mic"]["within_0_30_m"], 1)} m of {n(sep["mic"]["length_m"], 1)} m).',
         'Separate compartments or containment, cable insulation suited to the neighbouring voltage, and the amplifier topology: AV designer and electrical engineer.'],
        ['6', 'Life safety', f'{life["exit_signs"]} exit signs stay on in all {len(life["scene_counts"])} quick modes, including All off. ' + (
         'Their routes now leave DB-1 directly; before this review they left LC-1, the lighting-control enclosure. ' if life['source'] == ['DB1'] else f'They are fed from {", ".join(life["source"])}, not from their own way at DB-1. ')
         + 'No emergency escape luminaire is modelled.',
         'Keep E1 on its own protected way, independent of scene controls; design emergency lighting, its duration and its supply separately: Q14.'],
        ['7', 'Cables on timber', f'{n(timber)} m of the {n(r["mains_route_m"])} m of mains route runs along timber beams, the boarded roof lining or the timber chamber lining.',
         'Containment, fire performance, fixings without drilling structural timber, and no concealed joints: Q05, Q09. Fire designer and structural engineer.'],
        ['8', 'Weather and lightning', f'{open_points} wired points are open to the weather and {covered_points} more are under the veranda roofs. The highest are the dome floods at +{n(highest, 2)} m on the towers.',
         'Product ingress ratings, residual-current and surge protection, and coordination with the lightning-protection design: Q09.'],
        ['9', 'Exhaust circuit V1', f'{by["V1"]["points"]} fans, {n(by["V1"]["connected_w"])} W and {n(by["V1"]["longest_path_m"], 1)} m on one circuit: {n(by["V1"]["cases"][0]["loading_percent"])} % of a 10 A breaker in S1, '
         f'and a {by["V1"]["cases"][1]["comparison_breaker_a"]} A breaker with {by["V1"]["cases"][1]["comparison_area_mm2"]} mm² in the hotter, more bunched S2 case.',
         'Split into front gable, wing gables and service room. This also allows ventilation by zone.'],
        ['10', 'Fans over people', f'{len(ceiling)} ceiling fans hang on {n(ceiling[0]["drop_from_anchor_m"], 2)} m rods with the blades {n(min(f["lowest_moving_part_above_floor_m"] for f in ceiling), 2)} m above the floor. '
         f'The lowest wall or exhaust fan is {n(min(f["lowest_moving_part_above_floor_m"] for f in other_fans), 2)} m above its floor.',
         'Blade heights pass the 2.3 m screen. Rod, bracket, anti-sway restraint and secondary retention are a structural hold.'],
    ]
    w(table(['No.', 'Subject', 'Calculated evidence', 'Action and owner'], rows, ['---:', '---', '---', '---']))
    w('')
    w('## 2. The walk round the church')
    w('')
    w('The route starts at the boards behind the altar and goes forward to the towers, as a visitor with the 3D model would follow it in **Simulator → Wiring → Systems only**. '
      'Each wired point is counted once, in the zone where it stands. Connected watts are catalogue maxima of fixed equipment; socket ratings are not included.')
    w('')
    w(table(['Zone', 'Lights', 'Fans', 'Speakers', 'Mics', 'Sockets', 'Exit signs', 'Connected W', 'Full service W', 'Within 2.5 m reach', 'Under veranda roof', 'Open to weather'],
            [[z['zone'], z['light'], z['fan'], z['loudspeaker'], z['microphone'], z['socket'], z['exit sign'], n(z['connected_fixed_w']), n(z['full_service_w']), z['within_reach'], z['covered_exterior'], z['open_to_weather']] for z in zones]))
    w('')
    zmap = {z['zone']: z for z in zones}

    def circuits_of(name): return ', '.join(zmap[name]['circuits'])
    w(f'1. **Service room and boards** ({circuits_of("Service room and boards")}). DB-1, LC-1, FC-1 and the AV-1 rack stand on the back wall, with feeds of '
      '2.6 m, 3.4 m and 5.8 m between them. All circuits of the church except the front start here, so this room needs clear working space, labelling and a main isolator that the '
      'sacristan can reach. Four door lanterns hang 2.30 m above the floor, within reach. The room is also the vesting room: board doors should lock.')
    w(f'2. **Sanctuary** ({circuits_of("Sanctuary")}). Accent and key lights sit high on the chamber walls and beams (up to +{n(zmap["Sanctuary"]["highest"]["level_m"], 1)} m); their feeds run behind the '
      'removable timber lining. The two microphone lines run under the floor, away from every mains route. The two sanctuary outlets are on the axis-10 piers, 0.70 m above the side platform. '
      'Nothing electrical was added for the new carved corpus: it is lit by the two existing crucifix accents on L3.')
    w(f'3. **Wings** ({circuits_of("Wing B (ministers)")}). Each wing has two chandeliers on L8, two wall fans on F5 and one loudspeaker, all on the held wing review. '
      'Their feeds cross the wing roof in a covered soffit route. Reading light, air speed and noise in the wings still miss the brief (see the wing record).')
    w(f'4. **Nave** ({circuits_of("Nave")}). The busiest zone: {zmap["Nave"]["wired_points"]} wired points. Lighting, fan and loudspeaker trunks, the DB-2 feeder and the socket circuits share the two '
      'wall bands above the openings, then rise to the beams. This shared band is where separation, bunching (derating) and access for maintenance must be designed. '
      f'Ceiling-fan blades are {n(min(f["lowest_moving_part_above_floor_m"] for f in ceiling), 2)} m above the floor.')
    w(f'5. **Entrance hall and DB-2** ({circuits_of("Entrance hall and DB-2")}). DB-2 stands inside the main doors on side B at the end of the {n(s1["db2_feeder_m"], 1)} m feeder. '
      'The four front-gable exhaust fans and the two trial circulators are here; the circulators are off in every quick mode.')
    w(f'6. **Verandas and side paths** ({circuits_of("Verandas and side paths")}). {zmap["Verandas and side paths"]["covered_exterior"]} points are under the veranda roofs and '
      f'{zmap["Verandas and side paths"]["open_to_weather"]} are open to the weather (steps, paths, courtyard horns). The lowest lantern is {n(zmap["Verandas and side paths"]["lowest"]["height_above_floor_m"], 2)} m above the paving.')
    w(f'7. **Roof, eaves and gables** ({circuits_of("Roof, eaves and gables")}). Festival strings on the ridge and eaves, side floods and the wing-gable exhaust fans: {zmap["Roof, eaves and gables"]["wired_points"]} points, '
      'all outside, reached only with roof access.')
    w(f'8. **Towers, façade and front stage** ({circuits_of("Towers, façade and front stage")}). {zmap["Towers, façade and front stage"]["wired_points"]} points, all open to the weather, up to +{n(highest, 2)} m. '
      f'The statues\' hidden light lines and candles (L10) are {n(by["L10"]["connected_w"])} W in total. The two lockable event cabinets stand inside the tower porches on buried routes of '
      f'{n(sum(b["length_m"] for b in r["buried_routes"] if b["circuit"] == "P3"), 2)} m and {n(sum(b["length_m"] for b in r["buried_routes"] if b["circuit"] == "P4"), 2)} m; they are off in every quick mode.')
    w('')
    w('## 3. Circuit screens')
    w('')
    w('Case S1: 230 V, power factor 0.9, 45 °C, four bunched circuits. Case S2: 220 V, power factor 0.8, 50 °C, six bunched circuits. Both are unconfirmed comparison cases from '
      '[cable-design-inputs.json](cable-design-inputs.json). The table shows S1; the last area column shows S2.')
    w('')
    rows = []
    for c in circuits:
        a, b = c['cases']
        rows.append([f'{c["circuit"]}', c['source'], c['points'], n(c['connected_w']) if c['connected_w'] is not None else f'{c["socket_rating_a"]} A rating', n(a['design_current_a'], 1), a['comparison_breaker_a'], n(a['loading_percent']),
                     n(c['longest_path_m'], 1), f'{n(a["vdrop_percent_at_minimum_area"], 2)} @ {a["minimum_area_mm2"]}', n(a['circuit_budget_percent'], 0), a['comparison_area_mm2'] or '–', b['comparison_area_mm2'] or '–',
                     n(a['fault_a_at_minimum']), n(10 * a['comparison_breaker_a']), n(a['loop_allowance_ohm_type_c_at_minimum'], 2)])
    w(table(['Circuit', 'From', 'Points', 'Connected W', 'Design A', 'Breaker A', 'Load %', 'Longest path m', 'Drop % @ mm²', 'Budget %', 'Area S1 mm²', 'Area S2 mm²', 'Far-end fault A', 'Type C trips at A', 'Loop allowance Ω'], rows,
            ['---', '---'] + ['---:'] * 13))
    w('')
    w('How to read it:')
    w('')
    w('- **Design A** is connected load ÷ (U × PF). **Breaker** is the smallest standard rating at or above 1.25 × design current; for sockets it is the circuit rating. No trip curve or product is selected.')
    w('- **Drop %** is from the board that feeds the circuit to its worst point, at 1.25 × the catalogue load of fixed equipment with the current falling at each tap, or with the whole socket rating at the farthest outlet. '
      'Formula and constants as in the [cable review](cable-load-review.md): ΔU ≤ 2 I (R + X) L, R = 23.7/S Ω/km, X = 0.08 Ω/km. **Budget** is 3 % (lighting) or 5 % (other) from DB-1 less 1 % kept for the feeder.')
    w('- **Area** is the smallest table size, not below the smallest usual size, that passes both the ampacity comparison (breaker ≤ table current × temperature factor × grouping factor) and the drop budget. '
      'It is one size for the whole circuit. The older route-level review can show a different size on a single route because it shares the drop between trunk and branch.')
    w('- **Far-end fault** is 0.95 × U ÷ loop resistance of line and protective conductor at the smallest usual size (1.5 mm² lighting, 2.5 mm² fans and 16 A sockets, 6 mm² 32 A sockets), circuit only. '
      '**Loop allowance** is the impedance still available for the supply, the feeder and the board before a type C breaker (10 × rating) stops tripping instantaneously. '
      'A negative or small value means the circuit depends on residual-current protection or a larger conductor. The earthing system and real loop impedance are unknown (Q02, Q03).')
    w('')
    w('## 4. Supply and the DB-2 feeder')
    w('')
    rows = []
    for s in (s1, s2):
        rows.append([s['case_id'], n(s['fixed_planning_a'], 1), n(s['single_phase_fixed_plus_indoor_a'], 1), n(s['single_phase_everything_a'], 1), ' / '.join(n(x, 1) for x in s['three_phase_a']), n(s['three_phase_neutral_a'], 1)])
    w(table(['Case', 'Fixed equipment × 1.25 (A)', '+ indoor sockets (A)', '+ event points (A)', 'Three phases, everything (A per phase)', 'Neutral (A)'], rows))
    w('')
    w('The single-phase columns add socket ratings to fixed equipment with no diversity: an upper comparison, not a maximum-demand calculation. The three-phase column places each circuit on the '
      'lightest phase, largest first; the neutral value assumes equal power factors and no harmonics. Which loads really run together, and any agreed diversity, are for the designer (Q08).')
    w('')
    w(f'DB-2 carries {n(s1["db2_fixed_planning_a"], 1)} A of fixed equipment (with reserve) and {n(s1["event_socket_rating_a"])} A of event rating. Voltage drop on the {n(s1["db2_feeder_m"], 1)} m feeder, case S1:')
    w('')
    w(table(['Feeder mm²', 'Comparison ampacity (A)', 'One phase, fixed only (%)', 'One phase, with events (%)', 'Three phases, with events (%)'],
            [[f['area_mm2'], n(f['ampacity_a'], 1), n(f['single_phase_fixed_percent'], 2), n(f['single_phase_with_events_percent'], 2), n(f['three_phase_with_events_percent'], 2)] for f in s1['db2_feeder']]))
    w('')
    w(f'On three phases the feeder carries about {n(s1["db2_with_events_a"] / 3, 1)} A per phase if the two event points and the front lighting are spread evenly. '
      'The ampacity column uses the three-loaded-conductor table, so it applies to that case directly.')
    w('')
    w('## 5. Safety screens from the model geometry')
    w('')
    w(f'**Fans.** {len(ceiling)} ceiling fans: lowest moving part {n(min(f["lowest_moving_part_above_floor_m"] for f in ceiling), 2)} m above the floor, on {n(ceiling[0]["drop_from_anchor_m"], 2)} m rods from the purlins. '
      f'{len(other_fans)} wall, circulator and exhaust fans: lowest {n(min(f["lowest_moving_part_above_floor_m"] for f in other_fans), 2)} m. Product instructions for unguarded ceiling fans usually ask for blades above 2.3 m; all are above it. '
      'The mass and sway of a fan on a five-metre rod over the congregation is the real question, and it is a structural hold.')
    w('')
    w(f'**Within reach.** {len(reach)} wired points are less than 2.5 m above the floor they stand on: '
      + ', '.join(f'{v} {k}{"s" if v > 1 and not k.endswith("s") else ""}' for k, v in sorted(reach_kinds.items())) + '. '
      'The sockets are meant to be reached and are planned with shutters and 30 mA protection. The four service-room door lanterns at 2.30 m need a suitable enclosure and fixing height check.')
    w('')
    w('**Weather exposure by circuit** (model envelope only; the product ratings are not selected):')
    w('')
    w(table(['Circuit', 'Open to weather', 'Under veranda roof', 'Interior', 'Highest point (m)'],
            [[x['label'], x['open_to_weather'], x['covered_exterior'], x['interior'], n(x['highest_point_m'], 2)] for x in r['exterior_circuits']]))
    w('')
    w(f'**Signal lines and mains.** Sampled every 0.25 m along each signal route: loudspeaker routes {n(sep["audio"]["within_0_30_m"])} m of {n(sep["audio"]["length_m"])} m within 0.30 m of a mains route '
      f'({n(sep["audio"]["within_0_05_m"])} m within 0.05 m); microphone routes {n(sep["mic"]["within_0_30_m"], 2)} m of {n(sep["mic"]["length_m"], 1)} m. The loudspeaker trunks follow the same wall bands as the lighting '
      'trunks and the DB-2 feeder. The microphone lines keep their own route under the floor.')
    w('')
    w('**Where the mains routes run** (model centre lines):')
    w('')
    names = {'above-main-beam': 'On top of the main beams', 'above-side-beam': 'On top of the side beams', 'roof-pendant': 'Above the roof lining to pendants', 'roof-local': 'Roof route to a roof fitting',
             'chamber-lining': 'Behind the timber chamber lining', 'wall-roof-trunk': 'Wall bands above the openings, covered soffit crossing at the wings', 'tower-wall': 'Tower piers and walls',
             'tower-cornice': 'Behind tower cornices', 'entrance-wall': 'Entrance wall band and piers', 'entrance-gable': 'Front gable above the terrace', 'outer-wall': 'Outer arcade and wing-gable walls',
             'side-wall': 'Side-wall and pier drops', 'rear-wall': 'Rear wall band', 'service-ceiling': 'Service-room ceiling', 'underfloor-event': 'Buried duct to the tower event points', 'feeder': 'Board-to-board feeds'}
    w(table(['Route type', 'Length (m)'], [[names.get(k, k), n(v, 1)] for k, v in sorted(r['route_methods_m'].items(), key=lambda kv: -kv[1])]))
    w('')
    w(f'Of these, **{n(timber)} m** lie on timber (beam tops, roof lining, chamber lining). The buried event routes total {n(sum(b["length_m"] for b in r["buried_routes"]), 2)} m; duct, depth, draw pits and sealing are not designed.')
    w('')
    w(f'**Life safety and quick modes.** Exit signs lit: {", ".join(f"{k} {v}" for k, v in life["scene_counts"].items())}. '
      f'The indoor sockets stay live in All off ({"yes" if life["indoor_sockets_live_in_all_off"] else "no"}); the event points are on in no quick mode ({"confirmed" if not life["event_points_on_in_any_scene"] else "NOT confirmed"}). '
      'Exit signs are shown for location only. Emergency lighting, its duration and its supply need their own design.')
    w('')
    w('## 6. Efficiency')
    w('')
    w(f'Model assumptions: {n(e["service_hours"], 1)} h per service and {n(e["services_per_month"])} services per month; a tariff setting of {n(e["tariff_setting"])} per kWh whose currency and rate are not verified. '
      'These are modelled estimates of fixed equipment during services, not metered consumption. Standby, the AV rack, sockets and use between services are excluded.')
    w('')
    w(table(['Quick mode', 'W', 'Lighting W', 'Fans W', 'kWh per service', 'kWh per month', 'Cost per month (model tariff)'],
            [[x['scene'], n(x['watts']), n(x['by_category_w']['light']), n(x['by_category_w']['fan']), n(x['kwh_per_service'], 2), n(x['kwh_per_month']), n(x['cost_per_month_at_model_tariff'])] for x in e['scenes']]))
    w('')
    w('Largest circuits in the full evening service: ' + '; '.join(f'{c["label"]} {n(c["full_service_w"])} W' for c in top) + '.')
    w('')
    w(f'**Lighting.** Interior lighting in the full service is {n(e["interior_lighting_w_full_service"])} W over {n(e["floor_area_m2"])} m² of floor (hall and wings from the model\'s floor levels): '
      f'**{n(e["lighting_power_density_w_m2"], 2)} W/m²**. The 368 sampled seats average {n(e["seat_lux"]["mean"])} lux on the book (maintained), from {n(e["seat_lux"]["min"])} to {n(e["seat_lux"]["max"])} lux. '
      'The average is well above the 200 lux brief while some seats are below it, so the remaining lighting task is distribution, not more power. '
      f'Catalogue efficacy of the fittings averages {n(e["overall_lm_per_w"])} lm/W; these are planning values until products are selected.')
    w('')
    w(table(['Lighting circuit', 'Fittings', 'Lumens', 'W', 'lm/W'], [[x['label'], x['fittings'], n(x['lumens']), n(x['watts']), n(x['lm_per_w'])] for x in e['efficacy']]))
    w('')
    w(f'**Exterior lighting.** {", ".join(c["circuit"] for c in exterior_light)} together draw {n(exterior_w)} W in the full service, {n(100 * exterior_w / light_w)} % of all lighting power. '
      f'The façade and tower floods (L6, {n(by["L6"]["full_service_w"])} W) are the largest lighting circuit in the church. If the front lighting (L6, L9, L10: {n(e["facade_w_full_service"])} W) also ran four hours every night, '
      f'that alone would be about {n(e["facade_kwh_per_year_if_4_h_nightly"])} kWh a year, against {n(e["annual_service_kwh_full_scene"])} kWh for every service of the year at the full scene. '
      'A time switch with a curfew and a dimmed late setting is the largest saving available.')
    w('')
    w('**Fans** (catalogue planning values):')
    w('')
    w(table(['Fan type', 'Number', 'Speed 1', 'Speed 2', 'Speed 3'],
            [[f['product'], f['count']] + [f'{sp["watts"]} W · {n(sp["m3_h_per_w"])} (m³/h)/W · {sp["dba"]} dBA' for sp in f['speeds']] for f in e['fans']], ['---', '---:', '---', '---', '---']))
    w('')
    w(f'A ceiling fan moves four to five times more air per watt than the wall and exhaust fans. From speed 2 to speed 3 it takes {n(100 * (cf[2]["watts"] / cf[1]["watts"] - 1))} % more power for '
      f'{n(100 * (cf[2]["flow_m3_s"] / cf[1]["flow_m3_s"] - 1))} % more air, and it is {cf[2]["dba"] - cf[1]["dba"]} dBA louder. Use the ceiling fans first and the wall fans only when the church is full. '
      'The wing fans and the exhaust fans run in the Prayer and Cleaning modes; a mode without them would save power when few people are present.')
    w('')
    w(f'**Cable losses.** At full-service currents the final circuits lose about {n(e["loss_w_minimum_areas"])} W of {n(e["final_circuit_mains_w_full_service"])} W ({n(e["loss_percent_minimum_areas"], 1)} %) with the smallest usual cables. '
      f'The DB-2 feeder carries {n(e["db2_feeder_full_service_a"], 1)} A in that scene and loses {n(e["db2_feeder_loss"][0]["loss_w"], 1)} W at 10 mm² or {n(e["db2_feeder_loss"][-1]["loss_w"], 1)} W at 50 mm². '
      'Energy lost in cables is small: cable sizes here are decided by voltage drop, protection and heat, not by running cost.')
    w('')
    w(f'**Standing loads.** The exit signs ({n(e["exit_sign_w"])} W) burn continuously: about {n(e["exit_sign_kwh_per_year_continuous"])} kWh a year, which the service-only figures above do not show. '
      'Drivers, amplifiers, the mixer and control gear also draw power when idle; none of it is known. Measure it at commissioning and provide one clearly marked switch that isolates everything except life-safety circuits.')
    w('')
    w('## 7. Method and limits')
    w('')
    w('- Source: the default model loaded headless (`scripts/lib/study_model.cjs`), through `scripts/export_electrical_loads.cjs` (which first checks that the model equals the exports and the six registers) and '
      '`scripts/export_electrical_safety.cjs`. A saved browser layout is a different configuration and is not read.')
    w('- Formulas, the ampacity table, the breaker ratings and the two comparison cases are those of the existing [cable review](cable-load-review.md), imported from `scripts/electrical_review.py`. '
      'They are international comparison references, not verified Vietnamese requirements; the adopted QCVN/TCVN editions and clauses are not established for this project (ENG-001).')
    w('- Fixed-equipment watts are catalogue planning values, not nameplates. Inrush, harmonics, power factor per product, starting currents of fan motors and LED-driver leakage currents (which matter for residual-current devices) are not modelled.')
    w('- Fault currents omit the supply, the earthing system, the feeder and the boards, so they are upper values. Disconnection times, selectivity, short-circuit withstand and surge protection are not checked.')
    w('- Zones, reach and weather exposure come from item positions and the model\'s floor levels and room envelope. They show where to look; they are not a survey and not an ingress-protection assessment.')
    w('- The separation screen compares route centre lines. Routes drawn on the same line may be meant for separate compartments of one containment; that detail does not exist yet.')
    w('- Energy figures are scene estimates. The three-phase allocation is one balanced example, not a board schedule.')
    w('')
    w('Not checked in this review: earthing and bonding of metal chandeliers, fans and tower fittings; lightning protection; emergency lighting; fire stopping; conduit fill and supports; the AV rack supply; '
      'control hardware and its failure states; anything on site.')
    w('')
    return '\n'.join(out)
